FRONT-END-BOOTCAMP-PLUS-5/itGun

app/api/user/badges/route.ts

api method 변경
- api method GET으로 하기로 정한 api여서 수정했습니다.

fix: badge 목록 조회 api  메소드 변경

---

.github/workflows/ci.yml
app/api/user/info/route.ts
backend/application/user/info/dtos/UpdateUserInfoDto.ts
backend/application/user/info/usecases/UpdateUserInfoUsecase.ts
backend/domain/repositories/UserRepository.ts
backend/infrastructure/repositories/PrUserRepository.ts
package.json

사용자 정보 수정 API 개발
Closes #4 
없음
빌드 에러로 다른 작업도 포함되어 있어요 ...

사용자 정보 수정 API 개발

---

app/api/user/info/route.ts
backend/application/user/info/dtos/DeleteUserDto.ts
backend/application/user/info/usecases/DeleteUserUsecase.ts
backend/domain/repositories/UserRepository.ts
backend/infrastructure/repositories/PrUserRepository.ts

회원 탈퇴 기능을 위한 API 추가
Closes #25 
없음
현재 회원 탈퇴는 soft delete가 아닌 단순 삭제 처리입니다.

회원 탈퇴 API 개발

---

app/api/user/info/route.ts
backend/application/user/info/dtos/GetUserInfoRequestDto.ts
backend/application/user/info/dtos/GetUserInfoResponseDto.ts
backend/application/user/info/usecases/GetUserInfoUsecase.ts
backend/infrastructure/repositories/PrUserRepository.ts

이 PR은 어떤 변경사항을 담고 있나요? 관련 이슈가 있다면 연결해주세요.
Closes #5
아래 작업사항 수정했습니다 

Feat/5 회원 정보 조회 

---

static/exercises/exercises-data-ko.json

exerciseDB API의 exercise 데이터 영한 작업
Closes #44

docs: #44 exercise 디테일 영한 번역 작업 파일

---

ds/components/atoms/button/Button.stories.tsx
ds/components/atoms/button/Button.tsx
ds/components/atoms/button/Button.types.ts
ds/styles/tokens/button/sizes.ts
ds/styles/tokens/button/variants.ts

Button 공통 컴포넌트 개발
( Closes #52 )
<div style="display: flex; gap: 10px; align-items: flex-start;">
</div>

[디자인시스템] Button 공통 컴포넌트 개발

---

app/api/user/logs/[id]/route.ts
app/api/user/logs/route.ts
backend/application/user/logs/constants/badgeConstants.ts
backend/application/user/logs/services/BadgeAchievementService.ts
backend/application/user/logs/services/BadgeDeletionService.ts
backend/application/user/logs/services/badge-achievement/ConsecutiveDaysBadgeService.ts
backend/application/user/logs/services/badge-achievement/FirstWorkoutBadgeService.ts
backend/application/user/logs/services/badge-achievement/RecordBadgeService.ts
backend/application/user/logs/services/badge-achievement/WeeklyWorkoutBadgeService.ts
backend/application/user/logs/usecases/CreateLogUsecase.ts
backend/application/user/logs/usecases/DeleteLogUsecase.ts
backend/domain/repositories/LogRepository.ts
backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
backend/infrastructure/repositories/PrLogRepository.ts

운동 기록 삭제 API 트랜잭션 적용 및 등록 및 삭제 전반적인 리팩토링
This closes #91 

운동기록 및 운동 기록 삭제 API 리팩토링

---

ds/components/molecules/toast/Toast.tsx

Toast 컴포넌트 width 수정
Closes #98 
| ![before](https://github.com/user-attachments/assets/d292bc2b-e5c9-40a0-b698-b915cea4dbe4) | ![after](https://github.com/user-attachments/assets/4fa025b2-7df7-47d9-81a2-a1a3b18fd071) |

[디자인시스템] Toast 컴포넌트 width 수정

---

app/components/loading/LoadingCharacter.tsx
app/components/loading/LoadingText.tsx
app/loading.tsx
static/svgs/burky.tsx
utils/character.ts

로딩 페이지
(Closes #105 )
https://github.com/user-attachments/assets/f875a916-e8b6-4579-975a-ae4d101cc22c
- loading.tsx root에 넣어두었습니다!
- default character asset을 static/svgs 하위에 burky.tsx로 넣어두었습니다. 필요하시면 여기있는 svg를 사용하시면 됩니다

[페이지] 로딩페이지

---

app/user/logs/components/CalendarHeader.tsx
app/user/logs/components/LogList.tsx
app/user/logs/page.tsx
app/user/logs/types.ts
hooks/useGetUserLogs.ts

- `useSuspenseQuery` 사용으로 인한 상태 초기화 해결 및 리팩토링
This closes #162 

log 목록 조회 중 상태 초기화 문제 해결

---

app/menus/page.tsx

메뉴 페이지 하단 여백 수정
This closes #175 

[QA] 메뉴 페이지 하단 여백 수정

---

app/exercises/components/constants.ts
backend/infrastructure/repositories/PrExerciseRepository.ts

운동조회 api 다중 선택관련 수정
( Closes #176 )
|<img width="421" height="747" alt="스크린샷 2025-08-24 오후 11 58 00" src="https://github.com/user-attachments/assets/5b184bf9-0fef-47b2-a49e-bd285a8235e0" />|<img width="425" height="747" alt="스크린샷 2025-08-24 오후 11 58 20" src="https://github.com/user-attachments/assets/5a4dbe25-508c-4474-bd4f-5f7e7fbfba21" />|
- 검색결과 
- 필터에 스미스 머신 추가됨

[QA] 운동조회 페이지  - get api 수정

---

app/user/gauges/page.tsx

게이지 페이지 하단 여백 추가
( Closes #179 )
|<img width="422" height="750" alt="스크린샷 2025-08-25 오전 12 14 04" src="https://github.com/user-attachments/assets/2aa4a9fd-70f3-4b5e-9288-497bfe051980" />|<img width="429" height="751" alt="스크린샷 2025-08-25 오전 12 14 19" src="https://github.com/user-attachments/assets/35defe3d-70fe-461b-b235-10d630249e59" />|

[QA] 게이지 페이지 하단 여백 수정

---

ds/components/molecules/progressBar/ProgressBar.tsx

progress bar 배경 색 변경
(예: Closes #186 )
|<img width="352" height="237" alt="스크린샷 2025-08-25 오후 12 05 46" src="https://github.com/user-attachments/assets/8cc92c64-603b-4b4e-9b7b-bea11ae8888c" />|<img width="329" height="224" alt="스크린샷 2025-08-25 오후 12 06 10" src="https://github.com/user-attachments/assets/c0a76840-476b-4646-87fa-c8339fdd85c2" />|

[QA] 프로그레스 바 배경 색 수정

---

backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts

user body parts gauges get api 최신 값을 받아오지 않는 오류 수정
( Closes #200 )

[QA] 최신 게이지 조회 api fix

---

app/exercises/components/SearchInput.tsx
app/logs/components/DateTimeInput.tsx
app/logs/components/WorkoutLogSaveButton.tsx
app/logs/components/type.ts
app/logs/page.tsx
ds/components/molecules/workout/Workout.tsx
services/user/logs/createUserLogs.ts
utils/api/apiClient.ts

운동기록페이지 2차 QA 이슈 수정입니다.
(예: Closes #181)
2차 QA에 남겨주신 스크롤 시 최상단으로 이동하는 이슈가 어떨때 발생하는지 확인되지 않아서
계속 테스트해보고 발생하면 수정하겠습니다.

[QA] 운동기록 페이지 2차 qa 이슈 해결

---

app/layout.tsx

모바일에서 로그인, 회원가입, 메인 페이지 스크롤 안 생기도록 height 조정
이 PR은 어떤 변경사항을 담고 있나요? 관련 이슈가 있다면 연결해주세요.
Closes #203

[QA] 로그인, 회원가입, 메인 페이지 height 조정

---

prisma/schema.prisma

신기록 관련 테이블 userId 컬럼 unique 제약 조건 제거

[QA] 신기록 관련 테이블 userId 컬럼 unique 제약 조건 제거

---

app/exercises/components/ExerciseList.tsx
app/logs/components/AddWorkoutForm.tsx
app/logs/components/WorkoutLogSaveButton.tsx
app/logs/components/type.ts
app/logs/page.tsx
app/logs/types.ts
ds/components/molecules/workout/Workout.tsx
ds/components/molecules/workout/Workout.types.ts
utils/animations.ts

운동기록 시퀀스값 엉키는 에러 수정 /  해당 운동 전체 삭제 기능 추가
(예: Closes #211 )
https://github.com/user-attachments/assets/13cca16a-6baf-4cd8-8bdc-8a19b219ba47

[QA]운동 기록 페이지 3차 qa 오류 수정 최종

---

backend/application/user/logs/constants/userRecordConstants.ts

- 런닝 신기록 최소 기준 단위 불일치 문제 수정
This closes #239 

[QA] 런닝 신기록 최소 기준 수정
